---
title: "HIIT vs. MICT"
output:
  html_document:
    fig_caption: yes
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
  word_document:
    toc: yes
    toc_depth: '3'
---
This is designed to track study progress! Below is a weekly update.

```{r setup, include=FALSE}
# Load packages
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(table1)
library(lubridate)
library(shiny)
library(knitr)
library(kableExtra)
```


```{r demog, message=FALSE, warning=FALSE, echo=FALSE}
demog<-read.csv("/Users/aubreykr/Desktop/demog.csv")
```

## Where are participants this week?

This was last updated on `r format(Sys.Date(), format="%B %d, %Y")`.

```{r asd, message=FALSE, warning=FALSE, echo=FALSE}

# if missing, they have enrolled and update this
demog$enrollment_status[is.na(demog$enrollment_status) == TRUE] <- "Enrolled (not screened yet)"

demog$current_week <- factor(demog$current_week, levels=c("Week 1", "Week 2", "Week 3", "Week 4", "Week 5", "Week 6", "Week 7", "Week 8", "Week 9", "Week 10", "Week 11", "Week 12", "Week 13", "Week 14", "Week 15", "Week 16", "Week 17", "Week 18", "Beyond Week 18?"))

# number of participants currently training
num<-length(demog$record_id[demog$enrollment_status== "On-going Randomized" & is.na(demog$current_week)==FALSE])

# withdrawn participants: distinguish participants who started training vs. withdrew before study
demog$enrollment_status[demog$enrollment_status == "Withdrawn" & is.na(demog$start_month)==FALSE] <- "Withdrew after training"
demog$enrollment_status[demog$enrollment_status == "Withdrawn" & is.na(demog$start_month)==TRUE] <- "Withdrew before training"

```

```{r firstcode, message=FALSE, warning=FALSE, echo=FALSE}
# Snapshot of participant progress
demog %>% 
  filter(enrollment_status == "On-going Randomized" & current_week !="Not Training Yet") %>% 
  ggplot(aes(x=current_week, fill=factor(record_id))) + geom_bar() +  scale_x_discrete(drop = FALSE) + theme_bw()+
theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + xlab(paste0("Plot Last Updated:", sep=" ", Sys.Date())) + ggtitle(paste0(num, sep=" ", "individuals are currently training")) +   labs(fill = "Record ID") + theme(plot.title = element_text(hjust = 0.5))+ scale_y_continuous(breaks = seq(0, 30, 2)) + geom_text(aes(label = record_id, y = ..count..), 
            stat = "count", 
            position = position_stack(vjust = 0.5), 
            color = "black", size = 3) + ylim(c(0,2))
```

## How many workouts have they done?

### On-going participants
```{r workouts0, message=FALSE, warning=FALSE, echo=FALSE}
# Filter for participants who are on-going and not controls
training<-demog %>% 
  filter(enrollment_status == "On-going Randomized" & Group != "Control" & current_week !="Not Training Yet") %>% 
  dplyr::select(record_id, current_week, Group, quality_workouts_in_REDCap, total_workouts_in_REDCap, quality_fraction, training_status, sex, agegroup)

training %>% 
  arrange(current_week) %>% 
  kable() %>%
  kable_styling()
```


### Completed MICT participants
```{r workouts,message=FALSE, warning=FALSE, echo=FALSE}

# Filter for participants who are completed and MICT
completed_mict<-demog %>% 
  filter(enrollment_status == "Completed" & Group == "MICT") %>% 
  dplyr::select(record_id, quality_workouts_in_REDCap, percent_complete_of_36_wkts, sex, agegroup)

completed_mict %>% 
    arrange(quality_workouts_in_REDCap) %>% 
  kable() %>%
  kable_styling()
```

### Completed HIIT participants
```{r workouts2,message=FALSE, warning=FALSE, echo=FALSE}
# Filter for participants who are completed and HIIT
completed_hiit<-demog %>% 
  filter(enrollment_status == "Completed" & Group == "HIIT") %>% 
  dplyr::select(record_id, quality_workouts_in_REDCap, percent_complete_of_36_wkts, sex, agegroup)

completed_hiit %>% 
  arrange(quality_workouts_in_REDCap) %>% 
  kable() %>%
  kable_styling()
```

## Study Progress
```{r newppl, message=FALSE, warning=FALSE, echo=FALSE}
# Order levels of enrollment status
demog$enrollment_status <- factor(demog$enrollment_status, levels = c("Enrolled (not screened yet)", "Lost to Follow-Up", "Screen failed", "Withdrew before training","On-going Randomized", "Withdrew after training", "Completed"))

ggplot(aes(x=enrollment_status, fill = enrollment_status, alpha=0.8), data=demog)+geom_bar(stat="count")+
  ggtitle(paste("Total Participants: n=", sep="", length(unique(demog$record_id)))) + theme(plot.title = element_text(hjust = 0.5))+xlab("Participant Status")+ylab("Number")+scale_fill_discrete(name = "Group")+theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))+theme(legend.position = "none")+scale_y_continuous(limits=c(0,25), breaks=c(0,2,4,6,8,10,12,14,16,18,20,22,24))+ geom_text(aes(label=..count..),stat='count',vjust=1.5)
```


## Progress toward filling 4 strata
```{r progressstrata, message=FALSE, warning=FALSE, echo=FALSE}

# Create sex + agebin variable
demog$strata[demog$sex == "Female" & demog$agegroup == "18-35 yrs"]<-"F, 18-35"
demog$strata[demog$sex == "Female" & demog$agegroup == "35-55 yrs"]<-"F, 35-55"
demog$strata[demog$sex == "Male" & demog$agegroup == "18-35 yrs"]<-"M, 18-35"
demog$strata[demog$sex == "Male" & demog$agegroup == "35-55 yrs"]<-"M, 35-55"

cohort<-demog %>% 
  filter(enrollment_status == "On-going Randomized" | enrollment_status == "Completed")

# Progress Toward Filling 4 Strata (M, F, 18-35 yrs, 35-55 yrs)

cohort %>% 
  ggplot(aes(x=Group, fill=Group, alpha=0.8))+geom_bar(stat="count")+
  theme(plot.title = element_text(hjust = 0.5))+xlab("Group")+ylab("Number")+scale_fill_discrete(name = "Group")+facet_wrap(~strata)+
  geom_text(aes(label=..count..),stat='count',vjust=1.5) + 
  ggtitle(paste("On-going Randomized or Completed Study: n=", sep="", length(unique(cohort$record_id)))) + guides(alpha = "none")


completed_num<-cohort %>% 
  filter(enrollment_status == "Completed") %>% 
  count()

cohort %>% 
  filter(enrollment_status == "Completed") %>% 
  ggplot(aes(x=Group, fill=Group, alpha=0.8))+geom_bar(stat="count")+
  theme(plot.title = element_text(hjust = 0.5))+xlab("Group")+ylab("Number")+scale_fill_discrete(name = "Group")+facet_wrap(~strata)+
  geom_text(aes(label=..count..),stat='count',vjust=1.5) + 
  ggtitle(paste0(completed_num, sep=" ", "Completed")) + guides(alpha = "none")




```


*Thanks everybody for your hard work!*


```{r vo2checking, message=FALSE, warning=FALSE, echo=FALSE, include=FALSE}
## Workout adherence and VO2 max

# #library(readxl)
# #vo2<-read_xlsx("/Users/aubreykr/Desktop/VO2_prelim_analysis/Yair_condensed_VO2_1_6_24.xlsx")
# 
# # remove missing rows
# #vo2<-vo2 %>% 
#   #filter(is.na(record_id)==FALSE)
# 
# # change to baseline, endpoint labels
# vo2<-vo2 %>% 
#   mutate(Timepoint = case_when(Timepoint == "V1" ~ "Baseline",
#                                Timepoint == "V2" ~ "Endpoint"))
# 
# # rearrange timepoint to front of column
# vo2<-vo2 %>%
#   relocate(Timepoint, .after=record_id) %>% 
#   arrange(record_id, Timepoint)
# 
# # Calculated variables for VO2, VT1, VT2 
# 
# # % change in VO2 max
# for (i in 1:nrow(vo2)) {
#   if( i %% 2 == 1) { vo2$Peak_VO2_change[i] = 0 }
#   if (i %% 2 == 0) {  vo2$Peak_VO2_change[i] = (vo2$VO2_Peak_mLkg[i] - vo2$VO2_Peak_mLkg[i-1]) /  vo2$VO2_Peak_mLkg[i-1] * 100}
# } 
# 
# 
# # VT1
# for (i in 1:nrow(vo2)) {
#   if( i %% 2 == 1) { vo2$VT1_change[i] = 0 }
#   if (i %% 2 == 0) { vo2$VT1_change[i] = vo2$VT1_vo2[i] - vo2$VT1_vo2[i-1]}
# } 
# 
# # VT2
# for (i in 1:nrow(vo2)) {
#   if( i %% 2 == 1) { vo2$VT2_change[i] = 0 }
#   if (i %% 2 == 0) { vo2$VT2_change[i] = vo2$VT2_vo2[i] - vo2$VT2_vo2[i-1]}
# } 
# 
# # HR 
# for (i in 1:nrow(vo2)) {
#   if( i %% 2 == 1) { vo2$Peak_HR_change[i] = 0 }
#   if (i %% 2 == 0) { vo2$Peak_HR_change[i] = vo2$Peak_HR[i] - vo2$Peak_HR[i-1]}
# } 
# 
# # HR at VT1
# for (i in 1:nrow(vo2)) {
#   if( i %% 2 == 1) { vo2$VT1_HR_change[i] = 0 }
#   if (i %% 2 == 0) { vo2$VT1_HR_change[i] = vo2$VT1_HR[i] - vo2$VT1_HR[i-1]}
# } 
# 
# # HR at VT2
# for (i in 1:nrow(vo2)) {
#   if( i %% 2 == 1) { vo2$VT2_HR_change[i] = 0 }
#   if (i %% 2 == 0) { vo2$VT2_HR_change[i] = vo2$VT2_HR[i] - vo2$VT2_HR[i-1]}
# } 
# 
# # plot VO2 max at BL vs. EP
# #ggplot(aes(x=Timepoint, y=VO2_Peak_mLkg, color=factor(record_id), group=record_id), data=vo2) + geom_point() +
#  # geom_line(aes(group = record_id), linetype = "dashed") +
#  # labs(title = "VO2 Peak: Baseline vs. Endpoint", x = "Timepoint", y = "VO2 Peak (mL/kg)") + facet_wrap(~group) + theme(plot.title=element_text(hjust=0.5))
# 
# # length from first to last vo2 test
# length<-vo2[vo2$Timepoint == "Endpoint",]$date - vo2[vo2$Timepoint == "Baseline",]$date
# record_id<-unique(vo2$record_id)
# dates<-data.frame(cbind(record_id, length))
# vo2<-merge(vo2, dates)
# 
# # change to length in weeks not days
# vo2$length_weeks<-vo2$length / 7
# 
# # plot % change in VO2 max
# vo2 %>% 
#   filter(Timepoint=="Endpoint") %>% 
#   ggplot(aes(x=group, y=Peak_VO2_change)) + geom_boxplot() + geom_hline(yintercept=0, linetype="dotted") + geom_point() + 
#    stat_summary(
#     fun = median,
#     geom = "text",
#     vjust = -0.6,
#     size = 3.2,
#     aes(group = group, label = sprintf("%.2f", ..y..))
#   ) + ylab("Percent change in VO2 max") + xlab("Randomization Group") + ggtitle("Percent change in VO2 max after 12 Weeks") + theme(plot.title=element_text(hjust=0.5))
# 
# # add adherence data and dxa data to vo2 dataset
# subset<-demog %>% 
#   filter(enrollment_status == "Completed") %>% 
#   dplyr::select(record_id, sex, agegroup, total_workouts_in_REDCap, quality_workouts_in_REDCap, percent_complete_of_36_wkts)
# 
# vo2<-merge(vo2, subset, by="record_id")
# 
# # plot correlation between workout adherence and change in VO2
# 
# library(ggpubr)
# 
# vo2 %>% 
#   filter(Timepoint=="Endpoint" & group!="Con" & record_id!="4") %>% 
#   ggplot(aes(x=quality_workouts_in_REDCap, y=Peak_VO2_change, color=group)) + geom_point() + 
#     geom_smooth(method = "lm", se = FALSE, size=0.5) +  # Add linear regression line without confidence interval
#   labs(title = "Number Successful Workouts vs. % Change in VO2 max",
#        x = "Number Successful Workouts",
#        y = "Percent Change in VO2") + theme(plot.title=element_text(hjust=0.5)) + geom_hline(yintercept=0, linetype="dotted", size=0.8)+
#   stat_cor(method = "pearson")
# 
# vo2 %>% 
#   filter(Timepoint=="Endpoint" & group!="Con") %>% 
#   ggplot(aes(x=total_workouts_in_REDCap, y=Peak_VO2_change, color=group)) + geom_point() + 
#   labs(title = "Number Total Workouts vs. % Change in VO2 max",
#        x = "Number Total Workouts",
#        y = "Percent Change in VO2") + theme(plot.title=element_text(hjust=0.5)) + geom_hline(yintercept=0, linetype="dotted", size=0.8)
# 
# 
# # look at intervention length
# 
# vo2 %>% 
#   filter(Timepoint == "Endpoint" & group!="Con") %>% 
#   ggplot(aes(x=length_weeks, y=Peak_VO2_change, group=group, color=group)) + geom_point() +  geom_smooth(method = "lm", se = FALSE, size=0.5) + labs(title = "Number weeks between VO2 max visits vs. % Change in VO2 max",
#        x = "Number weeks between VO2 max visits",
#        y = "Percent Change in VO2") + theme(plot.title=element_text(hjust=0.5)) + geom_hline(yintercept=0, linetype="dotted", size=0.8)+
#    stat_cor(method = "pearson")
# 
# vo2 %>% 
#   filter(Timepoint == "Endpoint" & group!="Con") %>% 
#   ggplot(aes(x=length_weeks, y=quality_workouts_in_REDCap, group=group, color=group)) + geom_point() +  geom_smooth(method = "lm", se = FALSE, size=0.5) + labs(title = "Number weeks between VO2 max visits vs. num quality workouts",
#        x = "Number weeks between VO2 max visits",
#        y = "Number quality workouts in redcap") + theme(plot.title=element_text(hjust=0.5)) +
#    stat_cor(method = "pearson")
# 
# vo2<-vo2 %>% 
#   mutate(wkts_per_week = quality_workouts_in_REDCap / length_weeks)
# 
# # average number of workouts per week
# vo2 %>% 
#   filter(Timepoint == "Endpoint" & group!="Con" & record_id!="4") %>% 
#   ggplot(aes(x=wkts_per_week, y=Peak_VO2_change, group=group, color=group)) + geom_point() +  geom_smooth(method = "lm", se = FALSE, size=0.5) + labs(title = "Average num workouts per week vs. VO2 change",
#        x = "Average num workouts per week",
#        y = "Percent Change in VO2") + theme(plot.title=element_text(hjust=0.5)) +
#    stat_cor(method = "pearson") + geom_hline(yintercept=0, linetype="dotted", size=0.8)
# 
# 
# #model<-lm(percent_change_vo2 ~ sex + agegroup + weight_kg + quality_workouts_in_REDCap + length_weeks + group, data = test)
# #summary(model)
# 
# 
# vo2 %>% 
#   filter(Timepoint == "Endpoint" & group!="Con") %>% 
#   ggplot(aes(x=quality_workouts_in_REDCap, y=Peak_VO2_change, color=group)) + geom_point() + 
#   labs(title = "Changes by Sex, Age",
#        x = "Number Successful Workouts",
#        y = "Percent Change in VO2") + theme(plot.title=element_text(hjust=0.5)) + geom_hline(yintercept=0, linetype="dotted", size=0.8) + facet_wrap(~sex + agegroup)
# 
# 
# ```
# 
# ```{r vt1, message=FALSE, warning=FALSE, echo=FALSE}
# 
# ggplot(aes(x=Timepoint, y=VO2_Peak_mLkg), data=vo2) + geom_boxplot() + geom_point()+
#  labs(title = "VO2: Baseline vs. Endpoint", x = "Timepoint", y = "VO2 Peak (mL/kg)") + facet_wrap(~group) +
#   theme(plot.title=element_text(hjust=0.5)) + stat_compare_means(
#   method = "t.test", # You can also use "wilcox.test" for non-parametric test
#   label = "p.format",
#   paired = TRUE
# )
# 
# ggplot(aes(x=Timepoint, y=VT1_vo2), data=vo2) + geom_boxplot() + geom_point()+
#  labs(title = "VT1: Baseline vs. Endpoint", x = "Timepoint", y = "VO2 Peak (mL/kg)") + facet_wrap(~group) +
#   theme(plot.title=element_text(hjust=0.5)) + stat_compare_means(
#   method = "t.test", # You can also use "wilcox.test" for non-parametric test
#   label = "p.format",
#   paired = TRUE
# )
# 
# ggplot(aes(x=Timepoint, y=VT2_vo2), data=vo2) + geom_boxplot() + geom_point()+
#  labs(title = "VT2: Baseline vs. Endpoint", x = "Timepoint", y = "VO2 Peak (mL/kg)") + facet_wrap(~group) +
#   theme(plot.title=element_text(hjust=0.5)) + stat_compare_means(
#   method = "t.test", # You can also use "wilcox.test" for non-parametric test
#   label = "p.format",
#   paired = TRUE
# )
# 
# 
# ggplot(aes(x=Timepoint, y=Peak_HR), data=vo2) + geom_boxplot() + geom_point()+
#  labs(title = "VO2 HR: Baseline vs. Endpoint", x = "Timepoint", y = "VO2 Peak (mL/kg)") + facet_wrap(~group) +
#   theme(plot.title=element_text(hjust=0.5)) + stat_compare_means(
#   method = "t.test", # You can also use "wilcox.test" for non-parametric test
#   label = "p.format",
#   paired = TRUE
# )
# 
# ggplot(aes(x=Timepoint, y=VT1_HR), data=vo2) + geom_boxplot() + geom_point()+
#  labs(title = "VT1 HR: Baseline vs. Endpoint", x = "Timepoint", y = "VO2 Peak (mL/kg)") + facet_wrap(~group) +
#   theme(plot.title=element_text(hjust=0.5)) + stat_compare_means(
#   method = "t.test", # You can also use "wilcox.test" for non-parametric test
#   label = "p.format",
#   paired = TRUE
# )
# 
# ggplot(aes(x=Timepoint, y=VT2_HR), data=vo2) + geom_boxplot() + geom_point()+
#  labs(title = "VT2 HR: Baseline vs. Endpoint", x = "Timepoint", y = "VO2 Peak (mL/kg)") + facet_wrap(~group) +
#   theme(plot.title=element_text(hjust=0.5)) + stat_compare_means(
#   method = "t.test", # You can also use "wilcox.test" for non-parametric test
#   label = "p.format",
#   paired = TRUE
# )

```

```{r scoringefficacy, message=FALSE, warning=FALSE, echo=FALSE, include=FALSE}

# motiv<-read.csv("/Users/aubreykr/Desktop/exselfefficacy.csv")
# 
# motiv<-motiv %>% 
#   rename(Timepoint = redcap_event_name) %>% 
#   dplyr::select(-c(exeffiency_date_enrolled, exercise_selfefficacy_complete)) %>% 
#   mutate(Timepoint = case_when(Timepoint == "scr_bl_ep_arm_1" ~ "Baseline",
#                                Timepoint == "week_12_ep_surveys_arm_1" ~ "Endpoint",
#                                Timepoint == "month_6_arm_1" ~ "Month 6"))
# 
# # self-efficacy score ranges from 9-28; sum the 9 questions.
# motiv$efficacy_score <- rowSums(motiv[, 3:11])
# 
# # combine efficacy with vo2 data
# motiv<-motiv %>% 
#   dplyr::select(record_id, Timepoint, efficacy_score)
#  
# motiv$record_id <- as.numeric(motiv$record_id)
# 
# vo2<-left_join(vo2, motiv, by=c("record_id", "Timepoint"))
# 
# vo2 %>% 
#   filter(record_id != "8" & record_id != "10" & record_id != "29") %>% 
#   ggplot(aes(x=Timepoint, y=efficacy_score)) + geom_boxplot() + geom_point()+
#   labs(title = "Exercise Self-Efficacy: Baseline vs. Endpoint", x = "Timepoint", y = "Exercise Self-Efficacy (Score 9-36)") + facet_wrap(~group) +
#   theme(plot.title=element_text(hjust=0.5)) + stat_compare_means(
#   method = "t.test", # You can also use "wilcox.test" for non-parametric test
#   label = "p.format",
#   paired = TRUE
# )
# 
# vo2 %>% 
#   filter(record_id != "8" & record_id != "10" & record_id != "29") %>% 
#   ggplot(aes(x=Timepoint, y=efficacy_score, group=group, color=factor(record_id))) + geom_point()  + geom_line(aes(group = record_id), linetype = "dashed") + facet_wrap(~group)
# 
# # plot VO2 max at BL vs. EP
# #ggplot(aes(x=Timepoint, y=VO2_Peak_mLkg, color=factor(record_id), group=record_id), data=vo2) + geom_point() +
#  # geom_line(aes(group = record_id), linetype = "dashed") +
#  # labs(title = "VO2 Peak: Baseline vs. Endpoint", x = "Timepoint", y = "VO2 Peak (mL/kg)") + facet_wrap(~group) + theme(plot.title=element_text(hjust=0.5))
# 
# # make demographics tables
# demog<-vo2 %>% 
#   filter(Timepoint == "Baseline")
# 
# label(demog$sex) <- "Sex"
# label(demog$agegroup) <- "Age Group"
# table1(~sex + agegroup | group, data=demog, overall=F, caption="Demographics for Completed Participants")
```


